### ISSUE TITLE
SUGGESTION: a way to install KSSL **without** replacing the PD-Launcher

### ISSUE THREAD

**Issue by Lisias** [R-T-B/KSSL#3]
Hi,

I came to my attention that bluntly replacing the PD-Launcher will cause Steam to restore it back on each Game Verify, what is unfortunate because people using SSD's now and then ends up needing to to it to the unavoidable SSD's bit rotting as it gets old (yeah, I have a Steam Deck, and my NVMe is starting to show its age).

At the same time, there're a lot of people insisting on the Steam Launcher's hack, what's screwing up a lot of things on KSP (and not only on some add'ons) no matter what they say.

So, in an attempt to solve both problem above, how about an alternative installing option where the KSSL executable would be named 'KSSLauncher', and then the user would edit the Steam Launcher to invoke it instead of the PDLauncher? Its a pretty simple edit (replace PD with KSS), and it will solve the problems above.

**Comment by R-T-B** [comment]
Yeah, that could be done by a simple renaming of the current EXE...  basically just a documentation update.  I'll look into it right after I finish the next Kopernicus release (which is really backlogged courtesy my main file server crashing), , it sounds like an ok idea.

If for some reason Kopernicus takes extra long, I'll try to update the docs to support that within say...  a week or two.  No more.  Thanks for the idea.

**Comment by R-T-B** [comment]
I did some research into this.  Unfortunately, it appears impossible due to the required use of absolute paths in the steam launch options.  Furthermore, steam launch options does not preserve the absolute path's working directory like it should, making me have to choose between hardcoding potential install paths (ick) or just not supporting this.  Sadly, I am going with the latter for now.  Thanks for the idea though!
